### ISSUE TITLE
OS X and Linux releases

### ISSUE THREAD

**Issue by samhh** [ProTechnologist/WallStyler#1]
How far along would you say this is? This is exactly what I've been looking for on my non-Linux machines (where I use Variety).

**Comment by ProTechnologist** [comment]
Hopefully within next 10 days.

I'm in the middle of adding a few more features by coming weekend that includes the easy-to-install setup on windows platform (and hopefully a portable version). Once this is done, I'll start working on (first) Linux and (then) OS X releases so my guess is about 10 days or so.

**Comment by ProTechnologist** [comment]
I have released a new version (v.0.3) of WallStyler including the following:
1. Windows setup (using InnoSetup - tested on Windows 10)
2. Linux Release (untested)
3. Mac setup (tested on MacBook Air - Thanks to Wajeeh for helping me out on this)

In the case of Darwin/Mac, a Virtual Disk is created and you can run the WallStyler using following steps on mac:
1. Download .dmg file and copy it on desktop.
2. Double click on the .dmg file, and it'll create a new folder (virtual disk) with the same as of .dmg file.
3. Open the newly created folder and launch WallStyler
4. The WallStyler should run.

Being a purely Windows platform developer, I'm still in the process of learning how to properly create setup/installer for the mac and linux platform.

**Comment by samhh** [comment]
Hey @ProTechnologist, great to see an OS X release!

Some feedback:
- The install process is fairly standard, don't worry about that.
- Is there an option yet to filter by resolution? 1366x768 wallpapers are dominating the array of options but they're too low res for any of the machines that I use.
- An option in OS X (possibly Linux) to minimize up to the system menu bar would be fantastic. I'm guessing that unless I leave it open in the dock it won't be able to auto-change wallpapers?

Let me knwo.

**Comment by ProTechnologist** [comment]
Thanks for the positive feedback @SamHH 

I, too, agree that there are too many (but quality) wallpapers of resolution 1366x786 that is also why, my testing environment is also of resolution 1366x786.

WallStyler should work for other resolutions too and there are couple of options to go about it.
Please check this screenshot when you're finding and downloading wallpapers manually:
http://screencast.com/t/Ldv4ThnB5jcv
When MRW (My Resolution Wallpapers) is enabled, it should only show the wallpapers of your screen's resolution. (Tested on 1366x786 and 1920×1080).

If you wish to setup a filter so that scheduler can download wallpapers automatically for you, you can setup the resolution preferences here: http://screencast.com/t/OhJuKMEtWWk

Plus, I'm also aware of the fact that this WallStyler is missing the WiKi notes that explains how to use this app effectively. I'll start working on it on coming weekend that may or may not include a video.

Hope, this helps. :-)
If you find any issues/bugs at all, please feel free to let me know as I'll fix them up in the process of including Flickr as a next source of wallpapers for the WallStyler.

**Comment by ProTechnologist** [comment]
@SamHH 
I totally forgot to mention that when on Windows platform and app is minimized, it effectively changes the wallpapers after downloading them. Since I don't have much experience of Mac OS and Linux so there is a learning curve for me. I'm also working on it but it may take some time for me to include this feature but this is definitely a high priority for me as this feature is a must from the User Experience point of view regardless of the platform.

**Comment by samhh** [comment]
Cool, will do. Think this issue can be closed now :-)
